### ISSUE TITLE
Unloaded chunks

### ISSUE THREAD

**Issue by andreasdc** [SuicidalKids/IonSpigot#10]
When I tp to chunk at 0, 0 I see unloaded chunk. When I tp somewhere else and tp back I see normal chunks.

**Comment by Samsuik** [comment]
Any steps on how to reproduce this? I tried logging in at 0,0 tping to a random location and then back, logging in at a random location and then teleporting to 0,0 back and to 0,0 again. I didn't notice any chunks not loading properly. 

Are you running the latest build? I reverted 3381d44 5 days ago due to it causing chunks to not load properly when moving about and when you login.

**Comment by andreasdc** [comment]
@SuicidalKids ChunkProviderServer class is mostly SportPaper

**Comment by Samsuik** [comment]
Not sure what you mean by that.

**Comment by andreasdc** [comment]
SportPaper's version

**Comment by andreasdc** [comment]
@SuicidalKids I can check with your latest version

**Comment by andreasdc** [comment]
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /root/IonSpigot/IonSpigot-Server of /root/IonSpigot/pom.xml does not exist @
[ERROR] Child module /root/IonSpigot/IonSpigot-API of /root/IonSpigot/pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project me.suicidalkids.ion:parent:dev-SNAPSHOT (/root/IonSpigot/pom.xml) has 2 errors
[ERROR]     Child module /root/IonSpigot/IonSpigot-Server of /root/IonSpigot/pom.xml does not exist
[ERROR]     Child module /root/IonSpigot/IonSpigot-API of /root/IonSpigot/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by Samsuik** [comment]
> 
> 
> [INFO] Scanning for projects...
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [ERROR] Child module /root/IonSpigot/IonSpigot-Server of /root/IonSpigot/pom.xml does not exist @
> [ERROR] Child module /root/IonSpigot/IonSpigot-API of /root/IonSpigot/pom.xml does not exist @
> @
> [ERROR] The build could not read 1 project -> [Help 1]
> [ERROR]
> [ERROR] The project me.suicidalkids.ion:parent:dev-SNAPSHOT (/root/IonSpigot/pom.xml) has 2 errors
> [ERROR] Child module /root/IonSpigot/IonSpigot-Server of /root/IonSpigot/pom.xml does not exist
> [ERROR] Child module /root/IonSpigot/IonSpigot-API of /root/IonSpigot/pom.xml does not exist
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

This can happen due to the project not being able to be built, there may be an error somewhere above that message.

**Comment by andreasdc** [comment]
@SuicidalKids 
/IonSpigot# ./build.sh
Downloading unmapped vanilla jar...
Applying class mappings...
Applying member mappings...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587)
        at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java                                                                                                                                                             :706)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
        at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:69)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
Failed to apply member mappings.
[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$ReflectUtils

**Comment by andreasdc** [comment]
@SuicidalKids if you can send me ChunkProviderServer src I can test it

**Comment by andreasdc** [comment]
Reverting 3381d44  didn't fix this issue. Also when joining to unloaded chunk for the first time, I don't see any blocks.

**Comment by andreasdc** [comment]
1. I join the server somewhere.
2. I tp to 0, 0.
3. I tp somewhere else.
4. I tp back to 0,0.
5. Everything is working.
6. I quit the server.
7. I repeat and on 1st teleport to 0,0 I don't see chunks.
8. I tp somewhere else.
9. When I tp back to 0,0 i see chunks normally.

I noticed that lowering entityPlayer's view distance is making it behave different.

**Comment by andreasdc** [comment]
@SuicidalKids keepSpawnInMemory disabled is creating this bug
