### ISSUE TITLE
Please make IonSpigot java 16 compatible?

### ISSUE THREAD

**Issue by richiedevs** [SuicidalKids/IonSpigot#12]
IonSpigot works fine on java 8, but when running it with Java 16, it returns with the error:

```java
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.apache.commons.lang3.JavaVersion.atLeast(org.apache.commons.lang3.JavaVersion)" because "org.apache.commons.lang3.SystemUtils.JAVA_SPECIFICATION_VERSION_AS_ENUM" is null
        at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1413)
        at org.bukkit.craftbukkit.Main.main(Main.java:23)
```

I believe it would be a nice addition to let IonSpigot be able to run on Java 16, and it would offer more compatibility between using different java versions, as an example - minecraft 1.17 and 1.18 requires something like java 11 or java 16 to run, and this is why I'm requesting this. I hope IonSpigot adds Java 16 support

**Comment by richiedevs** [comment]
I think the 0001-POM-Changes.patch file in PaperSpigot-Server-Patches causes this error, because it contains 
```java
if (!SystemUtils.isJavaVersionAtLeast(JavaVersion.JAVA_1_8)) {
```

**Comment by Sculas** [comment]
No. This is not the case.
The reason Java 16 won't work on IonSpigot is due to the fact that Minecraft 1.8.8 and some 1.8 forks like IonSpigot use an older version of Netty that doesn't support the Java 11 stuff. You need to update Netty and fix a big mess of code to make it work with Java 11+. After that, you'll find out a lot of plugins are broken now :) Then you'll need to patch these, using Reflection or bytecode editing.

**Comment by richiedevs** [comment]
Got it, well - i usually custom code my plugins so plugins shouldnt be an issue for me

**Comment by Samsuik** [comment]
I'm not going to be adding support for later versions of java anytime soon. I don't know how to do this properly, I tried this out on another jar of mine a while ago. Updating netty and removing the java version check but it led to protocollib sometimes locking up the server when starting up. I didn't check to see if this was a plugin issue. I'm open for pull requests on this.

**Comment by Sculas** [comment]
The latest version of ProtocolLib fixed that. (4.7.0)

**Comment by Samsuik** [comment]
I might give that a try then. I was running 4.5.1 during my testing.

**Comment by richiedevs** [comment]
Thats awesome, would love java 11/16 support

**Comment by Samsuik** [comment]
I did some work on this in the netty-update branch. It does appear to work with the minimal testing I've done so far. I'm able to run Ion on my other system which is running linux with Java 11 and connect with my laptop and vise versa. Running ProtocolLib, Viaversion, Viabackwards and Viarewind I was able to connect using 1.17 on my laptop to my other system.

**Comment by Sculas** [comment]
Note though that iirc, Citizens doesn't work correctly and needs to be patched using Javassist. But it might be different now
